import Footer from '../components/Footer'

const sections = [
  {
    title: 'Use of the website',
    body: 'You may use GuffGPT for lawful personal, educational, and professional purposes. You agree not to misuse the website, attempt to disrupt its operation, or use it to create harmful, illegal, or abusive content.',
  },
  {
    title: 'AI-generated content',
    body: 'Responses generated by AI may be inaccurate or incomplete. You should verify important information before relying on it for education, medical, legal, financial, or professional decisions.',
  },
  {
    title: 'Intellectual property',
    body: 'The GuffGPT name, design, website content, and related materials belong to their respective owners. You may not copy or redistribute website assets without permission except where allowed by law.',
  },
  {
    title: 'Advertising and third-party links',
    body: 'This website may display advertisements or link to third-party websites. We are not responsible for third-party content, products, services, or privacy practices.',
  },
  {
    title: 'Limitation of liability',
    body: 'GuffGPT is provided as-is. We work to keep the website reliable, but we do not guarantee uninterrupted access or error-free responses. Use the service at your own discretion.',
  },
  {
    title: 'Contact',
    body: 'For questions about these terms, contact us at contact@guffgpt.com.',
  },
]

export default function Terms() {
  return (
    <>
      <main className="pt-[60px] overflow-hidden">
        <section className="relative px-5 pt-20 md:pt-28 pb-14 text-center">
          <div className="absolute inset-0 pointer-events-none" style={{ background: 'radial-gradient(ellipse 50% 40% at 50% 30%, rgba(99,102,241,0.16) 0%, transparent 70%)' }} />
          <div className="relative max-w-3xl mx-auto">
            <p className="inline-flex rounded-full border border-indigo-300/15 bg-indigo-400/10 px-4 py-2 text-[11px] font-semibold tracking-[0.2em] uppercase text-indigo-300 mb-4">Legal</p>
            <h1 className="text-4xl md:text-5xl lg:text-[3.5rem] font-black text-white tracking-[-0.04em] leading-[1.05]">Terms of Service</h1>
            <p className="mt-5 text-[15px] text-slate-500">Last updated: May 8, 2026</p>
          </div>
        </section>

        <section className="relative px-5 pb-24 md:pb-32">
          <div className="absolute right-0 top-10 h-72 w-72 rounded-full bg-fuchsia-500/10 blur-3xl pointer-events-none" />
          <div className="relative glass-panel max-w-3xl mx-auto rounded-[2rem] p-6 md:p-9">
            <p className="text-[16px] text-slate-400 leading-[1.85]">
              These terms explain the basic rules for using the GuffGPT website and related public content.
            </p>
            <div className="mt-10 space-y-8">
              {sections.map((section) => (
                <div key={section.title}>
                  <h2 className="text-xl font-bold text-white tracking-tight mb-3">{section.title}</h2>
                  <p className="text-[15px] text-slate-400 leading-[1.8]">{section.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
